### ISSUE TITLE
Better solution (external-secrets.io)

### ISSUE THREAD

**Issue by sobi3ch** [toVersus/aws-ssm-operator#6]
At the moment of writing this issue this repo hasn't been updated for almost 2 years (1y and 8m). So I assuming it's not maintain anymore. Moreover there is much better (flexible) and well maintain project called [external-secrets.io](https://external-secrets.io/). It supports not only [AWS Parameter Store](https://external-secrets.io/v0.5.6/provider-aws-parameter-store/) but also [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/), [HashiCorp Vault](https://www.vaultproject.io/), [Google Secrets Manager](https://cloud.google.com/secret-manager), [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/) and many more.

Because of that I suggest to add this information to readme file with suggestion to use this project instead of this one and archive this repository.

![archive-repo-github](https://user-images.githubusercontent.com/59183/181697309-a7beeb04-f4bf-443a-9732-44ad26819160.png)

**Comment by toVersus** [comment]
Thanks for your suggestion!

> At the moment of writing this issue this repo hasn't been updated for almost 2 years (1y and 8m). So I assuming it's not maintain anymore.

True. I changed my job and no longer maintain this tool any more.
I added the deprecation notice on README, so I will archive this repository.
